// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbbdgqiiacsazfgylelx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiYmRncWlpYWNzYXpmZ3lsZWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzQ4MjYsImV4cCI6MjA3MTYxMDgyNn0.cfzeQ4nVVjFz-FMhOOye-PUfuFqHXb1UCqMoDveqcz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});